app:
  password: ${APP_PASSWORD}
  cors-origin: ${APP_CORS_ORIGIN:http://localhost:3000}

server:
  servlet:
    session:
      timeout: 24h

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
