spring:
  profiles:
    default: local

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: true

server:
  servlet:
    session:
      timeout: 24h

app:
  password: 1234
  cors-origin: http://localhost:3000

logging:
  level:
    org:
      hibernate.SQL: DEBUG
