spring:
  datasource:
    url: jdbc:sqlite:./db/todo.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
